### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by haohanyang** [Kyuuhachi/Aureole#3]
https://aureole.kyuuhachi.dev/book is broken

**Comment by Kyuuhachi** [comment]
Looks like apache got oom'd a while ago...? Why'd it do that. I'm a programmer, not a sysadmin, dammit. Well, should be up again now.

**Comment by SonixApache** [comment]
Documentation site seems to have gone down again.

**Comment by Kyuuhachi** [comment]
Ugh, I hate sysadmin stuff. Switched out apache2 for caddy, hope it's more stable this way.
